services:
  db:
    image: postgres
    container_name: doer_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doer_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6000:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: doer_backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: doer_frontend
    ports:
      - "3000:3000"

  migrate:
    build: ./backend
    command: alembic upgrade head
    depends_on:
      - db
    env_file:
      - ./backend/.env.dev

volumes:
  postgres_data:
