services:
  db:
    build:
    container_name: doer_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doer_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5000:5432"

volumes:
  postgres_data:
